### PR TITLE
chore: update to rules_js 0.13.0

### PR DESCRIPTION
**Pull request by gregmagolan**
also removed internal dep on rules_ts

### CODE REVIEW

**Comment by alexeagle** [comment]
looks like it could just be deleted instead https://github.com/aspect-build/rules_esbuild/search?q=rules_ts

**Comment by gregmagolan** [comment]
in use in an example, https://github.com/aspect-build/rules_esbuild/search?q=aspect_rules_ts

**Comment by gregmagolan** [comment]
switch that to use plain old tsc?

**Comment by alexeagle** [comment]
ah thanks, doesn't seem like that example even benefits from typechecking so easiest thing is to change it to javascript?

**Review by alexeagle — APPROVED** [review]
🙏🏻

**Pull request merged**
