### PR TITLE
feat: add bundle=false support

### LINKED ISSUE #97: [FR]: Support for bundle=false
### What is the current behavior?

Currently `rules_esbuild` only runs `esbuild` with `bundle=true`.

### Describe the feature

Support `bundle=false` and properly propagate transitive dependencies and sources in this case.

### Fund our work

- [ ] Sponsor our open source work by donating a [feature bounty](https://opencollective.com/aspect-build/)

### PR DESCRIPTION
**Pull request by josephglanville**
Implements support for disabling bundling.

Fixes #97

### CODE REVIEW

**Comment by gregmagolan** [comment]
Thanks for the PR. Is the use case here to use esbuild as a transpiler instead of a bundler?

**Comment by josephglanville** [comment]
Essentially yes. I didn't get around to finishing this because we unfortunately chose to go a different way.

My eventual goal was to also introduce the possibility of using plugins in the esbuild wrapper too so that you can combine esbuild with Babel for instance. (specifically for handling [twin-macro](https://github.com/ben-rogerson/twin.macro))

I might pick this up again eventually but for now it's unlikely I end up finishing it.

**Comment by josephglanville** [comment]
I'm back to working on this. I will work on adding some tests for this feature and then mark the PR ready for review.

**Comment by gregmagolan** [comment]
Thanks for the PR @josephglanville. Sorry this one took so long to get it. Fell off the radar.

I rebased and added a commit to cleanup the new e2e test & fixup the providers when bundle is off.

Should be good to land now

**Review by gregmagolan — APPROVED** [review]

**Pull request merged**
